// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9XOCwldBDXvEzTEMwbThMSJuJVczIr0',
    appId: '1:1020196034079:web:b0108432ad3b6f969be72a',
    messagingSenderId: '1020196034079',
    projectId: 'afc-mobile-prod',
    authDomain: 'afc-mobile-prod.firebaseapp.com',
    storageBucket: 'afc-mobile-prod.firebasestorage.app',
    measurementId: 'G-XNH392L7PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADJXvNhUlRAEPVopr_gZltDYx88dB6-0s',
    appId: '1:1020196034079:android:b3ee29d1fb58791f9be72a',
    messagingSenderId: '1020196034079',
    projectId: 'afc-mobile-prod',
    storageBucket: 'afc-mobile-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5PBwZ2HnZ8jTXLYGkP3c4QSIHn3dAuX4',
    appId: '1:1020196034079:ios:c981d669b84e7c2c9be72a',
    messagingSenderId: '1020196034079',
    projectId: 'afc-mobile-prod',
    storageBucket: 'afc-mobile-prod.firebasestorage.app',
    iosBundleId: 'org.awesomefinancialcontrol.br',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5PBwZ2HnZ8jTXLYGkP3c4QSIHn3dAuX4',
    appId: '1:1020196034079:ios:f63882fd015d51829be72a',
    messagingSenderId: '1020196034079',
    projectId: 'afc-mobile-prod',
    storageBucket: 'afc-mobile-prod.firebasestorage.app',
    iosBundleId: 'com.example.afc',
  );
}
