// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjw1qS0CLZ54PF-jR3KW0qBbB979_xpdI',
    appId: '1:232489420015:web:c012985f1e41849be0c71a',
    messagingSenderId: '232489420015',
    projectId: 'afc-mobile-9f0dc',
    authDomain: 'afc-mobile-9f0dc.firebaseapp.com',
    storageBucket: 'afc-mobile-9f0dc.firebasestorage.app',
    measurementId: 'G-8T8SCE628W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKpeCewBT2fPh310NpIm4Odm-aP6IH1sc',
    appId: '1:232489420015:android:ddf4f8b945985eb0e0c71a',
    messagingSenderId: '232489420015',
    projectId: 'afc-mobile-9f0dc',
    storageBucket: 'afc-mobile-9f0dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9oRW9dNvsQdDc87ZMbe0MX54bqzIWrlw',
    appId: '1:232489420015:ios:0df039057836e455e0c71a',
    messagingSenderId: '232489420015',
    projectId: 'afc-mobile-9f0dc',
    storageBucket: 'afc-mobile-9f0dc.firebasestorage.app',
    iosClientId: '232489420015-6fuhju9gmth8q7mds785qs7hihtnfrn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.afc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9oRW9dNvsQdDc87ZMbe0MX54bqzIWrlw',
    appId: '1:232489420015:ios:0df039057836e455e0c71a',
    messagingSenderId: '232489420015',
    projectId: 'afc-mobile-9f0dc',
    storageBucket: 'afc-mobile-9f0dc.firebasestorage.app',
    iosClientId: '232489420015-6fuhju9gmth8q7mds785qs7hihtnfrn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.afc',
  );
}
