name: 🛠 Android CI / Build APK

on:
  push:
    branches: [ main ]
    # tags:    [ 'v*.*.*' ] # release tags
  pull_request:
    branches: [ main ]

permissions:
  contents: write # upload apk files
  actions:  read # read actions from github market place

concurrency: # only the last commit will run
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Cache pub deps  # optimize dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: ☕️ Setup Java (Temurin 17) # android apps require JAVA
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle # caches ~/.gradle/caches and ~/.gradle/wrapper

      - name: 🦋 Setup Flutter (v3.41.5)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.5'
          channel: 'stable'
          cache: true

      - name: 📦 Cache Android CMake 3.22.1 # avoids re-download during Gradle build
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/cmake/3.22.1
          key: android-cmake-3.22.1

      - name: 🔧 Pre-install Android CMake 3.22.1
        run: |
          echo y | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1" > /dev/null

      - name: 📥 Get dependencies
        run: flutter pub get

      - name: ✅ Run Analyzer
        run: flutter analyze

      - name: ✅ Run tests
        run: flutter test --coverage

      - name: 🏗️ Build APKs (dev)
        run: |
          flutter build apk --release --split-per-abi \
            --flavor dev \
            --target lib/main_dev.dart \
            --dart-define=CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}

      - name: 📦 Prepare artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/*.apk artifacts/

      # ─────────────── ONLY ON TAGS ───────────────
      - name: 🏷️ Create or update Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.16.0
        with:
          tag:       ${{ github.ref_name }}
          name:      Release ${{ github.ref_name }}
          artifacts: artifacts/*.apk
          token:     ${{ secrets.GITHUB_TOKEN }}
